blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/y3q8Geh
    about: Official Discord Server
  - name: Website
    url: https://hugebot.net
    about: See what HUGE can do for you
